pling = ""
harp = ""
bell = ""
chime = ""
bit = ""
flute = ""
xylophone = ""
iron_xylophone = ""
banjo = ""
guitar = ""
bass = ""
didgeridoo = ""
hat = ""
snare = ""
basedrum = ""

##############

bell += "4g.b.d.f#.G.f#.d.b.g.c.d.G.G...a."
bell += "3g;;b.d.f#.G;f#;e;d;;A;G.G.f#.G;f#;e;d;"
bell += ";c.e.G;A.B;A;G;e;;B.D.A;G.A;G;f;d#;"
bell += "G;A;f#;G.e.f#;e.d#;;B;A.A;G;e.f#;e.d#;;"
bell += ".d.e.G;D;C=-B;A;G;e;d#;A;;B;"
bell += "G=-"
bell += "bdG,bdG,bdG,bdG,bdG,bdG,bdG,bdG,bdG,bdG,bdG,bdG,beG,beG,beG,beG,beG,beG,beG,beG,beG,beG,beG,beG,ceG,ceG,ceG,ceG,ceG,ceG,ceG,ceG,ceG,ceG,ceG,ceG,"
bell += ".f#AD,f#AD.f#AD,f#AD.f#AD,f#AD;"

harp += "4=e=c=d="
harp += "3GBD===eBD==="
harp += "GCE===d#GC==="
harp += "dBD==.f#BD#-.eBD==.f#BD#-."
harp += "dGB=-dG#C=-eGC=-d#GC=-"

bass += "4&3&*&*&*&*&*"

##############

bass += ".d,d.d,d.d,d;"

bell += "g;b;d;bf#.bG;bf#;be;bd-bA;bG;bG.bf#;bG,"
bell += ".bf#;e,bd;;"
bell += "c;e;G;ceA.ceB;ceA;ceG;ce-"
bell += "c;e.G-cd#A.cdA#;cdA;f,cd#;;"
bell += "bA;bG.bG-bf#.bG;bf#;be;bd-"
bell += "g;b.d;bf#;bG;bf#;be;bd-"
bell += ";dD.cC,cC;bB.cC;bB;gG;e-"
bell += "c;e.G;cd#A;cd#A#;cd#A;f,cd#;;"
bell += "bG;bA;bf#;bG.be;bf#;e,bd#;;"
bell += "bG;bA;bf#;bG.be;bf#;e,bd#;;"
bell += "d;e;G.dD;cC,;;;;"
bell += "bB;aA;gG;e;d#;aA;;bB;"
bell += "bdG"

bass += "G.G,D.D,G.G,D.D,G.G,D.D,G.G,D.D,G.G,D.D,G.G,D.D,"
bass += "G.D,A.D,A#.D,B.D,"
bass += "c.c,G.G,c.c,G.G,c.c,G.G,c.c,G.G,"
bass += "d#.d#,C.C,d#.d#,C.C,d#.d#,C.C,d#.d#,C.C,"
bass += "G.G,D.D,G.G,D.D,G.G,D.D,G.G,D.D,"
bass += "G.G,D.D,G.G,D.D,G.D,A.D,A#.D,B.D,"
bass += "c.c,G.G,c.c,G.G,c.c,G.G,c.c,G.G,"
bass += "d#.d#,C.C,d#.d#,C.C,d#.d#,C.C,d#.d#,C.C,"
bass += "d.d,B.B,d.d,B.B,d.d,B.B,d#.d#,B.B,"
bass += "e.e,B.B,e.e,B.B,e.e,B.B,d#.d#,C.C,"
bass += "d.d,B.B,d.d,B.B,e.e,B.B,e.e,B.B,"
bass += "c.c,G.G,c.c,G.G,d#.d#,C.C,d#.d#,C.C,"
bass += "gG"
