pling = ""
harp = ""
bell = ""
chime = ""
bit = ""
xylophone = ""
banjo = ""
guitar = ""
bass = ""
didgeridoo = ""
hat = ""
snare = ""
basedrum = ""

pling += "&&"
pling += "B;A;f#-d....A,A,A.A.B.D.D.B."
pling += "E;D;B.A..f#.A.B;A;f#.e..e.d."
pling += "e;f#;d----.G;G;G."
pling += ".f#.-------"
pling += "&&&&"
pling += "B;A;f#-d....A,A,A.A.B.D.D.B."
pling += "E;D;B.A..f#.A.B;A;f#.e..e.d."
pling += "e;f#;d----.G;G;G."
pling += ".f#"

banjo += "&&&&&&&&&&"
banjo += "B;A;f#-d....A,A,A.A.B.D.D.B."
banjo += "E;D;B.A..f#.A.B;A;f#.e..e.d."
banjo += "e;f#;d----.G;G;G."
banjo += ".f#"

chime += "&&&&&&&&&&&&------G;G;G."
chime += ".f#"

xylophone += ".A,A,A.A,A.A,A.B-.A,A,A.A,A.A,A.G#-"
xylophone += ".A,A,A.A,A.A,A.B-.A,A,A.A,A.A,A.G#-"
xylophone += ".A,A,A.A,A.A,A.B-.A,A,A.A,A.A,A.G#-"
xylophone += ".A,A,A.A,A.A,A.B-.A,A,A.A,A.A,A.G#-"
xylophone += ".B,B,B.B,B.C#;B.A..E,E,E.E,E.F#;E.C#."
xylophone += ".A,A,A.A,A.A,A.B-.A,A,A.A,A.A,A.B-"

harp += "&&&&&&"
harp += "a-.a--c#.d-.d-.d-b-.b.--d-.c#.--"
harp += "a-.a--c#.d-.d-.d-b-.b.--d-.c#.--"

bass += "aaa----aaa----aaa----aaa----"
bass += "aaa----aaa---g#g#g#-#f#f#f-------ccc-bbb---bBB-g#G#G#----aaa----aaa----"
bass += "aaa-.aaa-eee.ggg.g#g#g#.aaa-.aaa-eee.ggg.g#g#g#.ddd-.ddd-aaa.ccc.ddd.eee;ccc;ddd-ggg.ccc.aaa."
bass += "aaa-.aaa-eee.ggg.g#g#g#.aaa-.aaa-eee.ggg.g#g#g#.ddd-.ddd-aaa.ccc.ddd.eee;ccc;ddd-ggg.ccc.aaa."
bass += "aaa----aaa---g#g#g#-#f#f#f-------ccc-bbb---bBB-g#G#G#----aaa"

hat += "-f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#---"
snare += "&&&&&-------f#,f#;-f#--f#--f#--f#--f#--f#--f#--f#,f#;-f#--f#--f#--f#--f#--f#--f#-.f#,f#,f#,f#;-f#--f#--f#--f#--f#--f#--f#--f#,f#;-f#--f#--f#--f#-"
basedrum += "&&&&&&f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--f#--"
